server:
  port: 8080

Spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlinetest?serverTimezone=UTC
    username: root
    password: 2875013802Ab
    driver-class-name: com.mysql.cj.jdbc.Driver





